# -*- coding: utf-8 -*-
"""Shared catalogue of journals, with ISSNs resolved from Crossref.

Field packs pick titles from here by name, so a journal has one tier and
one impact factor no matter which field is being read.  ISSNs are what the
ingest layer actually queries, so they must stay exact.

Generated by tools/gen_journals.py + tools/gen_catalog.py.

``tier``  1 = flagship, 2 = leading specialist, 3 = solid specialist
``jif``   approximate recent JCR impact factor, for display and sorting only
"""
from __future__ import annotations

TIER_LABELS = {
    1: {"en": "Flagship", "zh": "顶级期刊"},
    2: {"en": "Leading", "zh": "一流期刊"},
    3: {"en": "Specialist", "zh": "专业期刊"},
}

JOURNALS = [
    {"name": 'Nature Reviews Materials', "issn": ['2058-8437'], "tier": 1, "jif": 79.8, "publisher": 'Springer Science and Business Media LLC'},
    {"name": 'Chemical Reviews', "issn": ['0009-2665', '1520-6890'], "tier": 1, "jif": 51.4, "publisher": 'American Chemical Society'},
    {"name": 'Nature', "issn": ['0028-0836', '1476-4687'], "tier": 1, "jif": 50.5, "publisher": 'Springer Science and Business Media LLC'},
    {"name": 'Nature Energy', "issn": ['2058-7546'], "tier": 1, "jif": 49.7, "publisher": 'Springer Science and Business Media LLC'},
    {"name": 'Science', "issn": ['0036-8075', '1095-9203'], "tier": 1, "jif": 44.7, "publisher": 'American Association for the Advancement of Science (AAAS)'},
    {"name": 'Nature Catalysis', "issn": ['2520-1158'], "tier": 1, "jif": 42.8, "publisher": 'Springer Science and Business Media LLC'},
    {"name": 'Chemical Society Reviews', "issn": ['0306-0012', '1460-4744'], "tier": 1, "jif": 40.4, "publisher": 'The Royal Society of Chemistry'},
    {"name": 'Joule', "issn": ['2542-4351'], "tier": 1, "jif": 38.6, "publisher": 'Elsevier'},
    {"name": 'Nature Materials', "issn": ['1476-1122', '1476-4660'], "tier": 1, "jif": 37.2, "publisher": 'Springer Science and Business Media LLC'},
    {"name": 'Nature Nanotechnology', "issn": ['1748-3387', '1748-3395'], "tier": 1, "jif": 36.8, "publisher": 'Springer Science and Business Media LLC'},
    {"name": 'Nature Reviews Chemistry', "issn": ['2397-3358'], "tier": 1, "jif": 33.9, "publisher": 'Springer Science and Business Media LLC'},
    {"name": 'Progress in Materials Science', "issn": ['0079-6425', '1873-2208'], "tier": 1, "jif": 33.6, "publisher": 'Elsevier'},
    {"name": 'Energy & Environmental Science', "issn": ['1754-5692', '1754-5706'], "tier": 1, "jif": 32.4, "publisher": 'The Royal Society of Chemistry'},
    {"name": 'Nature Photonics', "issn": ['1749-4885', '1749-4893'], "tier": 1, "jif": 32.3, "publisher": 'Springer Science and Business Media LLC'},
    {"name": 'Materials Science and Engineering R Reports', "issn": ['0927-796X'], "tier": 1, "jif": 31.6, "publisher": 'Elsevier'},
    {"name": 'Electrochemical Energy Reviews', "issn": ['2520-8136', '2520-8489'], "tier": 1, "jif": 28.5, "publisher": 'Springer-Verlag'},
    {"name": 'Advanced Materials', "issn": ['0935-9648', '1521-4095'], "tier": 1, "jif": 27.4, "publisher": 'Wiley (John Wiley & Sons)'},
    {"name": 'Nature Sustainability', "issn": ['2398-9629'], "tier": 1, "jif": 25.7, "publisher": 'Springer Science and Business Media LLC'},
    {"name": 'Advanced Energy Materials', "issn": ['1614-6832', '1614-6840'], "tier": 1, "jif": 24.4, "publisher": 'Wiley (John Wiley & Sons)'},
    {"name": 'Nature Synthesis', "issn": ['2731-0582'], "tier": 1, "jif": 20.9, "publisher": 'Springer Science and Business Media LLC'},
    {"name": 'ACS Energy Letters', "issn": ['2380-8195'], "tier": 1, "jif": 19.3, "publisher": 'American Chemical Society'},
    {"name": 'Nature Chemistry', "issn": ['1755-4330', '1755-4349'], "tier": 1, "jif": 19.2, "publisher": 'Springer Science and Business Media LLC'},
    {"name": 'Chem', "issn": ['2451-9294'], "tier": 1, "jif": 19.1, "publisher": 'Elsevier'},
    {"name": 'Matter', "issn": ['2590-2385'], "tier": 1, "jif": 17.5, "publisher": 'Elsevier'},
    {"name": 'Angewandte Chemie Int. Ed.', "issn": ['1433-7851', '1521-3773'], "tier": 1, "jif": 16.1, "publisher": 'Wiley (John Wiley & Sons)'},
    {"name": 'Nature Communications', "issn": ['2041-1723'], "tier": 1, "jif": 15.7, "publisher": 'Springer Science and Business Media LLC'},
    {"name": 'J. Am. Chem. Soc. (JACS)', "issn": ['0002-7863', '1520-5126'], "tier": 1, "jif": 14.4, "publisher": 'American Chemical Society'},
    {"name": 'Science Advances', "issn": ['2375-2548'], "tier": 1, "jif": 12.5, "publisher": 'American Association for the Advancement of Science (AAAS)'},
    {"name": 'PNAS', "issn": ['0027-8424', '1091-6490'], "tier": 1, "jif": 9.4, "publisher": 'Proceedings of the National Academy of Sciences'},
    {"name": 'Nature Reviews Clean Technology', "issn": ['3005-0685'], "tier": 1, "jif": None, "publisher": 'Springer Science and Business Media LLC'},
    {"name": 'Nature Reviews Electrical Engineering', "issn": ['2948-1201'], "tier": 1, "jif": None, "publisher": 'Springer Science and Business Media LLC'},
    {"name": 'eScience', "issn": ['2667-1417'], "tier": 2, "jif": 42.9, "publisher": 'Elsevier'},
    {"name": 'Nano-Micro Letters', "issn": ['2150-5551', '2311-6706'], "tier": 2, "jif": 31.6, "publisher": 'Springer-Verlag'},
    {"name": 'Advanced Powder Materials', "issn": ['2772-834X'], "tier": 2, "jif": 28.6, "publisher": 'Elsevier'},
    {"name": 'InfoMat', "issn": ['2567-3165'], "tier": 2, "jif": 22.7, "publisher": 'Wiley (John Wiley & Sons)'},
    {"name": 'Materials Today', "issn": ['1369-7021'], "tier": 2, "jif": 21.1, "publisher": 'Elsevier'},
    {"name": 'Applied Catalysis B Environment and Energy', "issn": ['0926-3373'], "tier": 2, "jif": 20.2, "publisher": 'Elsevier'},
    {"name": 'Carbon Energy', "issn": ['2637-9368'], "tier": 2, "jif": 19.5, "publisher": 'Wiley (John Wiley & Sons)'},
    {"name": 'Energy Storage Materials', "issn": ['2405-8297'], "tier": 2, "jif": 18.9, "publisher": 'Elsevier'},
    {"name": 'Science Bulletin', "issn": ['2095-9273', '2095-9281'], "tier": 2, "jif": 18.8, "publisher": 'Elsevier'},
    {"name": 'SusMat', "issn": ['2692-4552'], "tier": 2, "jif": 18.7, "publisher": 'Wiley (John Wiley & Sons)'},
    {"name": 'Interdisciplinary Materials', "issn": ['2767-4401', '2767-441X'], "tier": 2, "jif": 18.6, "publisher": 'Wiley (John Wiley & Sons)'},
    {"name": 'Advanced Functional Materials', "issn": ['1616-301X', '1616-3028'], "tier": 2, "jif": 18.5, "publisher": 'Wiley (John Wiley & Sons)'},
    {"name": 'Nano Energy', "issn": ['2211-2855'], "tier": 2, "jif": 16.8, "publisher": 'Elsevier'},
    {"name": 'National Science Review', "issn": ['2053-714X', '2095-5138'], "tier": 2, "jif": 16.6, "publisher": 'Oxford University Press'},
    {"name": 'Accounts of Chemical Research', "issn": ['0001-4842', '1520-4898'], "tier": 2, "jif": 16.4, "publisher": 'American Chemical Society'},
    {"name": 'Renewable and Sustainable Energy Reviews', "issn": ['1364-0321'], "tier": 2, "jif": 16.3, "publisher": 'Elsevier'},
    {"name": 'ACS Nano', "issn": ['1936-0851', '1936-086X'], "tier": 2, "jif": 15.8, "publisher": 'American Chemical Society'},
    {"name": 'Advanced Science', "issn": ['2198-3844'], "tier": 2, "jif": 14.3, "publisher": 'Wiley (John Wiley & Sons)'},
    {"name": 'Journal of Energy Chemistry', "issn": ['2095-4956'], "tier": 2, "jif": 14.0, "publisher": 'Elsevier'},
    {"name": 'Aggregate', "issn": ['2692-4560'], "tier": 2, "jif": 13.9, "publisher": 'Wiley (John Wiley & Sons)'},
    {"name": 'Small Structures', "issn": ['2688-4062'], "tier": 2, "jif": 13.9, "publisher": 'Wiley (John Wiley & Sons)'},
    {"name": 'Chemical Engineering Journal', "issn": ['1385-8947'], "tier": 2, "jif": 13.3, "publisher": 'Elsevier'},
    {"name": 'Small', "issn": ['1613-6810', '1613-6829'], "tier": 2, "jif": 13.0, "publisher": 'Wiley (John Wiley & Sons)'},
    {"name": 'npj Flexible Electronics', "issn": ['2397-4621'], "tier": 2, "jif": 12.4, "publisher": 'Springer Science and Business Media LLC'},
    {"name": 'Materials Horizons', "issn": ['2051-6347', '2051-6355'], "tier": 2, "jif": 12.2, "publisher": 'The Royal Society of Chemistry'},
    {"name": 'ACS Catalysis', "issn": ['2155-5435'], "tier": 2, "jif": 11.3, "publisher": 'American Chemical Society'},
    {"name": 'Journal of Materials Chemistry A', "issn": ['2050-7488', '2050-7496'], "tier": 2, "jif": 10.7, "publisher": 'The Royal Society of Chemistry'},
    {"name": 'Small Methods', "issn": ['2366-9608'], "tier": 2, "jif": 10.7, "publisher": 'Wiley (John Wiley & Sons)'},
    {"name": 'Applied Energy', "issn": ['0306-2619'], "tier": 2, "jif": 10.1, "publisher": 'Elsevier'},
    {"name": 'Energy Conversion and Management', "issn": ['0196-8904'], "tier": 2, "jif": 9.9, "publisher": 'Elsevier'},
    {"name": 'ACS Materials Letters', "issn": ['2639-4979'], "tier": 2, "jif": 9.6, "publisher": 'American Chemical Society'},
    {"name": 'Nano Letters', "issn": ['1530-6984', '1530-6992'], "tier": 2, "jif": 9.6, "publisher": 'American Chemical Society'},
    {"name": 'npj Computational Materials', "issn": ['2057-3960'], "tier": 2, "jif": 9.4, "publisher": 'Springer Science and Business Media LLC'},
    {"name": 'Green Chemistry', "issn": ['1463-9262', '1463-9270'], "tier": 2, "jif": 9.3, "publisher": 'The Royal Society of Chemistry'},
    {"name": 'Device', "issn": ['0216-9185', '2746-8984'], "tier": 2, "jif": 8.7, "publisher": 'LP3M Universitas Sains Al Quran'},
    {"name": 'JACS Au', "issn": ['2691-3704'], "tier": 2, "jif": 8.5, "publisher": 'American Chemical Society'},
    {"name": 'Journal of Membrane Science', "issn": ['0376-7388'], "tier": 2, "jif": 8.4, "publisher": 'Elsevier'},
    {"name": 'Advanced Optical Materials', "issn": ['2195-1071'], "tier": 2, "jif": 7.9, "publisher": 'Wiley (John Wiley & Sons)'},
    {"name": 'Cell Reports Physical Science', "issn": ['2666-3864'], "tier": 2, "jif": 7.9, "publisher": 'Elsevier'},
    {"name": 'Chemical Science', "issn": ['2041-6520', '2041-6539'], "tier": 2, "jif": 7.6, "publisher": 'The Royal Society of Chemistry'},
    {"name": 'Chemistry of Materials', "issn": ['0897-4756', '1520-5002'], "tier": 2, "jif": 7.2, "publisher": 'American Chemical Society'},
    {"name": 'Solar RRL', "issn": ['2367-198X'], "tier": 2, "jif": 6.8, "publisher": 'Wiley (John Wiley & Sons)'},
    {"name": 'ACS Photonics', "issn": ['2330-4022'], "tier": 2, "jif": 6.5, "publisher": 'American Chemical Society'},
    {"name": 'EES Catalysis', "issn": ['2753-801X'], "tier": 2, "jif": None, "publisher": 'The Royal Society of Chemistry'},
    {"name": 'Energy Material Advances', "issn": ['2692-7640'], "tier": 3, "jif": 26.0, "publisher": 'American Association for the Advancement of Science (AAAS)'},
    {"name": 'Energy & Environmental Materials', "issn": ['2575-0356'], "tier": 3, "jif": 13.0, "publisher": 'Wiley (John Wiley & Sons)'},
    {"name": 'ACS Central Science', "issn": ['2374-7943', '2374-7951'], "tier": 3, "jif": 12.7, "publisher": 'American Chemical Society'},
    {"name": 'Green Energy & Environment', "issn": ['2468-0257'], "tier": 3, "jif": 12.6, "publisher": 'Elsevier'},
    {"name": 'Materials Futures', "issn": ['2752-5724'], "tier": 3, "jif": 12.0, "publisher": 'IOP Publishing'},
    {"name": 'Journal of Materials Science & Technology', "issn": ['1005-0302'], "tier": 3, "jif": 11.2, "publisher": 'Elsevier'},
    {"name": 'Nano Research', "issn": ['1998-0000', '1998-0124'], "tier": 3, "jif": 9.6, "publisher": 'Tsinghua University Press'},
    {"name": 'Chinese Chemical Letters', "issn": ['1001-8417'], "tier": 3, "jif": 9.4, "publisher": 'Elsevier'},
    {"name": 'EcoMat', "issn": ['2567-3173'], "tier": 3, "jif": 9.2, "publisher": 'Wiley (John Wiley & Sons)'},
    {"name": 'Journal of Energy Storage', "issn": ['2352-152X'], "tier": 3, "jif": 8.9, "publisher": 'Elsevier'},
    {"name": 'Rare Metals', "issn": ['1001-0521', '1867-7185'], "tier": 3, "jif": 8.6, "publisher": 'Wiley (John Wiley & Sons)'},
    {"name": 'Battery Energy', "issn": ['2768-1688', '2768-1696'], "tier": 3, "jif": 8.5, "publisher": 'Wiley (John Wiley & Sons)'},
    {"name": 'ACS Applied Materials & Interfaces', "issn": ['1944-8244', '1944-8252'], "tier": 3, "jif": 8.3, "publisher": 'American Chemical Society'},
    {"name": 'Journal of Power Sources', "issn": ['0378-7753'], "tier": 3, "jif": 8.1, "publisher": 'Elsevier'},
    {"name": 'Separation and Purification Technology', "issn": ['1383-5866'], "tier": 3, "jif": 8.1, "publisher": 'Elsevier'},
    {"name": 'ChemSusChem', "issn": ['1864-5631', '1864-564X'], "tier": 3, "jif": 7.5, "publisher": 'Wiley (John Wiley & Sons)'},
    {"name": 'International Journal of Hydrogen Energy', "issn": ['0360-3199'], "tier": 3, "jif": 7.2, "publisher": 'Elsevier'},
    {"name": 'ACS Sustainable Chemistry & Engineering', "issn": ['2168-0485'], "tier": 3, "jif": 7.1, "publisher": 'American Chemical Society'},
    {"name": 'Advanced Materials Technologies', "issn": ['2365-709X'], "tier": 3, "jif": 6.8, "publisher": 'Wiley (John Wiley & Sons)'},
    {"name": 'Fuel', "issn": ['0016-2361'], "tier": 3, "jif": 6.7, "publisher": 'Elsevier'},
    {"name": 'Journal of Catalysis', "issn": ['0021-9517', '1090-2694'], "tier": 3, "jif": 6.5, "publisher": 'Elsevier'},
    {"name": 'Progress in Photovoltaics Research and Applications', "issn": ['1062-7995', '1099-159X'], "tier": 3, "jif": 6.5, "publisher": 'Wiley (John Wiley & Sons)'},
    {"name": 'Solar Energy Materials and Solar Cells', "issn": ['0927-0248'], "tier": 3, "jif": 6.3, "publisher": 'Elsevier'},
    {"name": 'Journal of Materials Chemistry B', "issn": ['2050-750X', '2050-7518'], "tier": 3, "jif": 6.1, "publisher": 'The Royal Society of Chemistry'},
    {"name": 'Journal of Alloys and Compounds', "issn": ['0925-8388'], "tier": 3, "jif": 5.8, "publisher": 'Elsevier'},
    {"name": 'Journal of Materials Chemistry C', "issn": ['2050-7526', '2050-7534'], "tier": 3, "jif": 5.7, "publisher": 'The Royal Society of Chemistry'},
    {"name": 'Advanced Energy and Sustainability Research', "issn": ['2699-9412'], "tier": 3, "jif": 5.5, "publisher": 'Wiley (John Wiley & Sons)'},
    {"name": 'Electrochimica Acta', "issn": ['0013-4686'], "tier": 3, "jif": 5.5, "publisher": 'Elsevier'},
    {"name": 'ACS Applied Energy Materials', "issn": ['2574-0962'], "tier": 3, "jif": 5.4, "publisher": 'American Chemical Society'},
    {"name": 'ACS Applied Nano Materials', "issn": ['2574-0970'], "tier": 3, "jif": 5.3, "publisher": 'American Chemical Society'},
    {"name": 'Ceramics International', "issn": ['0272-8842'], "tier": 3, "jif": 5.1, "publisher": 'Elsevier'},
    {"name": 'Sustainable Energy & Fuels', "issn": ['2398-4902'], "tier": 3, "jif": 5.0, "publisher": 'The Royal Society of Chemistry'},
    {"name": 'Chemical Communications', "issn": ['1359-7345', '1364-548X'], "tier": 3, "jif": 4.9, "publisher": 'The Royal Society of Chemistry'},
    {"name": 'J. Phys. Chem. Lett.', "issn": ['1948-7185'], "tier": 3, "jif": 4.8, "publisher": 'American Chemical Society'},
    {"name": 'Batteries & Supercaps', "issn": ['2566-6223'], "tier": 3, "jif": 4.7, "publisher": 'Wiley (John Wiley & Sons)'},
    {"name": 'Electrochemistry Communications', "issn": ['1388-2481'], "tier": 3, "jif": 4.7, "publisher": 'Elsevier'},
    {"name": 'ACS Applied Polymer Materials', "issn": ['2637-6105'], "tier": 3, "jif": 4.4, "publisher": 'American Chemical Society'},
    {"name": 'Catalysis Science & Technology', "issn": ['2044-4753', '2044-4761'], "tier": 3, "jif": 4.4, "publisher": 'The Royal Society of Chemistry'},
    {"name": 'Chemical Engineering Science', "issn": ['0009-2509'], "tier": 3, "jif": 4.1, "publisher": 'Elsevier'},
    {"name": 'ChemCatChem', "issn": ['1867-3880', '1867-3899'], "tier": 3, "jif": 3.8, "publisher": 'Wiley (John Wiley & Sons)'},
    {"name": 'Physical Review Materials', "issn": ['2475-9953'], "tier": 3, "jif": 3.4, "publisher": 'American Physical Society'},
    {"name": 'J. Electrochem. Soc.', "issn": ['0013-4651', '1945-7111'], "tier": 3, "jif": 3.1, "publisher": 'The Electrochemical Society'},
    {"name": 'Solid State Ionics', "issn": ['0167-2738'], "tier": 3, "jif": 3.0, "publisher": 'Elsevier'},
    {"name": 'ACS Electrochemistry', "issn": ['2997-0571'], "tier": 3, "jif": None, "publisher": 'American Chemical Society'},
]

# ---- lookup tables -------------------------------------------------------
ISSN_TO_JOURNAL = {issn: j for j in JOURNALS for issn in j["issn"]}
ALL_ISSNS = sorted(ISSN_TO_JOURNAL)
BY_NAME = {j["name"]: j for j in JOURNALS}


def issns_for_tiers(max_tier: int = 3) -> list[str]:
    """Every ISSN belonging to a journal at or above ``max_tier``."""
    return sorted({i for j in JOURNALS if j["tier"] <= max_tier for i in j["issn"]})


def issns_for(names, max_tier: int = 3) -> list[str]:
    """ISSNs for a named subset -- what one field pack asks the ingest to scan."""
    wanted = set(names or ())
    return sorted({i for j in JOURNALS
                   if j["name"] in wanted and j["tier"] <= max_tier
                   for i in j["issn"]})


def unknown_names(names) -> list[str]:
    """Names a pack asks for that this catalogue does not have -- catches typos."""
    return sorted(n for n in (names or ()) if n not in BY_NAME)


def lookup(issns, container_title: str = "") -> dict | None:
    """Resolve a Crossref record to a catalogued journal, ISSN first then title."""
    for issn in issns or ():
        j = ISSN_TO_JOURNAL.get((issn or "").strip().upper())
        if j:
            return j
    key = " ".join((container_title or "").split())
    return BY_NAME.get(key)

