#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Merge the newly resolved journals into app/journals.py (the shared catalogue).

Field packs select titles from this one catalogue by name, so tiers and impact
factors stay consistent no matter which field a reader picks.
"""
import json, pathlib, re, sys
sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent.parent))
from app import journals as old

ISSN_RE = re.compile(r"^\d{4}-\d{3}[\dxX]$")
BOGUS = {"9999-9999"}

# tier: 1 flagship, 2 leading, 3 specialist;  jif: approximate recent JCR value
NEW_META = {
    "Nature Photonics": (1, 32.3), "Nature Catalysis": (1, 42.8),
    "Nature Synthesis": (1, 20.9), "Nature Reviews Electrical Engineering": (1, None),
    "Materials Science and Engineering R Reports": (1, 31.6),
    "Progress in Materials Science": (1, 33.6),
    "ACS Catalysis": (2, 11.3), "Applied Catalysis B Environment and Energy": (2, 20.2),
    "Green Chemistry": (2, 9.3), "EES Catalysis": (2, None),
    "Journal of Membrane Science": (2, 8.4), "Applied Energy": (2, 10.1),
    "Energy Conversion and Management": (2, 9.9),
    "Renewable and Sustainable Energy Reviews": (2, 16.3),
    "Solar RRL": (2, 6.8), "ACS Photonics": (2, 6.5),
    "Advanced Optical Materials": (2, 7.9), "npj Flexible Electronics": (2, 12.4),
    "Progress in Photovoltaics Research and Applications": (3, 6.5),
    "Solar Energy Materials and Solar Cells": (3, 6.3),
    "Journal of Catalysis": (3, 6.5), "ChemCatChem": (3, 3.8),
    "ChemSusChem": (3, 7.5), "Catalysis Science & Technology": (3, 4.4),
    "ACS Electrochemistry": (3, None),
    "International Journal of Hydrogen Energy": (3, 7.2),
    "Electrochemistry Communications": (3, 4.7), "Fuel": (3, 6.7),
    "Advanced Energy and Sustainability Research": (3, 5.5),
    "ACS Applied Nano Materials": (3, 5.3), "Journal of Materials Chemistry B": (3, 6.1),
    "Chemical Engineering Science": (3, 4.1),
    "Separation and Purification Technology": (3, 8.1),
}

rows = [dict(j) for j in old.JOURNALS]
have_names = {j["name"] for j in rows}
have_issns = {i for j in rows for i in j["issn"]}

added, skipped = 0, []
for rec in json.load(open("/tmp/journals_more.json")):
    if not rec.get("ok"):
        continue
    title = rec["title"].strip()
    issns = sorted({i for i in rec["issn"] if ISSN_RE.match(i) and i not in BOGUS})
    if not issns:
        skipped.append((title, "no valid ISSN")); continue
    if title in have_names:
        skipped.append((title, "already in catalogue")); continue
    clash = [i for i in issns if i in have_issns]
    if clash:
        skipped.append((title, "ISSN already used: %s" % clash)); continue
    if title not in NEW_META:
        skipped.append((title, "no tier/IF assigned")); continue
    tier, jif = NEW_META[title]
    rows.append({"name": title, "issn": issns, "tier": tier, "jif": jif,
                 "publisher": (rec.get("publisher") or "").strip()})
    have_names.add(title)
    have_issns.update(issns)
    added += 1

rows.sort(key=lambda r: (r["tier"], -(r["jif"] or 0), r["name"]))

body = ['# -*- coding: utf-8 -*-',
        '"""Shared catalogue of journals, with ISSNs resolved from Crossref.',
        '',
        'Field packs pick titles from here by name, so a journal has one tier and',
        'one impact factor no matter which field is being read.  ISSNs are what the',
        'ingest layer actually queries, so they must stay exact.',
        '',
        'Generated by tools/gen_journals.py + tools/gen_catalog.py.',
        '',
        '``tier``  1 = flagship, 2 = leading specialist, 3 = solid specialist',
        '``jif``   approximate recent JCR impact factor, for display and sorting only',
        '"""',
        'from __future__ import annotations', '',
        'TIER_LABELS = {',
        '    1: {"en": "Flagship", "zh": "顶级期刊"},',
        '    2: {"en": "Leading", "zh": "一流期刊"},',
        '    3: {"en": "Specialist", "zh": "专业期刊"},',
        '}', '',
        'JOURNALS = [']
for r in rows:
    body.append("    {{\"name\": {n!r}, \"issn\": {i!r}, \"tier\": {t}, \"jif\": {j!r}, "
                "\"publisher\": {p!r}}},".format(n=r["name"], i=r["issn"], t=r["tier"],
                                                 j=r["jif"], p=r["publisher"]))
body += [']', '',
 '# ---- lookup tables -------------------------------------------------------',
 'ISSN_TO_JOURNAL = {issn: j for j in JOURNALS for issn in j["issn"]}',
 'ALL_ISSNS = sorted(ISSN_TO_JOURNAL)',
 'BY_NAME = {j["name"]: j for j in JOURNALS}',
 '',
 '',
 'def issns_for_tiers(max_tier: int = 3) -> list[str]:',
 '    """Every ISSN belonging to a journal at or above ``max_tier``."""',
 '    return sorted({i for j in JOURNALS if j["tier"] <= max_tier for i in j["issn"]})',
 '',
 '',
 'def issns_for(names, max_tier: int = 3) -> list[str]:',
 '    """ISSNs for a named subset -- what one field pack asks the ingest to scan."""',
 '    wanted = set(names or ())',
 '    return sorted({i for j in JOURNALS',
 '                   if j["name"] in wanted and j["tier"] <= max_tier',
 '                   for i in j["issn"]})',
 '',
 '',
 'def unknown_names(names) -> list[str]:',
 '    """Names a pack asks for that this catalogue does not have -- catches typos."""',
 '    return sorted(n for n in (names or ()) if n not in BY_NAME)',
 '',
 '',
 'def lookup(issns, container_title: str = "") -> dict | None:',
 '    """Resolve a Crossref record to a catalogued journal, ISSN first then title."""',
 '    for issn in issns or ():',
 '        j = ISSN_TO_JOURNAL.get((issn or "").strip().upper())',
 '        if j:',
 '            return j',
 '    key = " ".join((container_title or "").split())',
 '    return BY_NAME.get(key)',
 '']
out = pathlib.Path("app/journals.py")
out.write_text("\n".join(body) + "\n", encoding="utf-8")
print("catalogue: %d journals (+%d new)" % (len(rows), added))
for name, why in skipped:
    print("  skipped %-52s %s" % (name, why))
